Repository ublue-os/bazzite, pull requests merged in 2024-09, with the labels that each got.

#1590 chore(docs): Minor cosmetic improvements and fixes
  docs/hooks/md_image_sizing.py
  docs/src/index.md
  docs/src/stylesheets/bazzite.css
Labels: documentation, size:M, lgtm

#1594 docs: Add missing automounting guides
  docs/hooks/cmdrun.py
  docs/src/Advanced/gnome-disks-automount-guide.md
  docs/src/Advanced/kde-automount-guide.md
Labels: documentation, size:S, lgtm

#1593 chore(just): Improve install-resolve ux
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: enhancement, size:XS, lgtm

#1582 chore(README-English): New documentation links
  README.md
Labels: documentation, size:S, lgtm

#1600 chore(docs): fix cmdrun breaking image url replacement
  .github/workflows/deploy_docs.yml
  docs/hooks/cmdrun.py
Labels: documentation, size:XS, lgtm

#1603 chore(docs): Minor improvements (again)
  docs/src/index.md
Labels: documentation, size:M, lgtm

#1581 chore(docs): Add auto-mount documentation (hidden)
  docs/src/Advanced/GNOME_Disks_Auto-Mount_Guide.md
  docs/src/Advanced/KDE_Partition_Manager_Auto_Mount_Guide.md
Labels: documentation, size:XS, lgtm

#1604 chore(docs): Hotfix
  docs/src/index.md
Labels: documentation, size:XS, lgtm

#1606 chore(docs): wtf is a mkdocs!???!?!?
  docs/mkdocs.yml
Labels: documentation, size:XS, lgtm

#1602 docs: Transcribe docs to github
  docs/hooks/cmdrun.py
  docs/src/Advanced/Auto-Mounting_Secondary_Drives.md
  docs/src/Advanced/Contributing_to_bazzite.md
  docs/src/Advanced/GNOME_Disks_Auto-Mount_Guide.md
  docs/src/Advanced/KDE_Partition_Manager_Auto_Mount_Guide.md
  docs/src/Advanced/Reset_Forgotten_User_Password.md
  docs/src/Advanced/creating_custom_image.md
  docs/src/Advanced/gnome-disks-automount-guide.md
  docs/src/Advanced/kde-automount-guide.md
  docs/src/Gaming/Common_gaming_issues.md
  docs/src/Gaming/Game_Launchers.md
  docs/src/Gaming/Hardware_compatibility_for_gaming.md
  docs/src/Gaming/Managing_and_modding_games.md
  docs/src/Gaming/index.md
  docs/src/General/Contributing_to_Bazzite.md
  docs/src/General/Desktop_Environment_Tweaks.md
  docs/src/General/FAQ.md
  docs/src/General/Installation_Guide/Installing_Bazzite_Framework_Laptop_13.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Framework_Laptop_16.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_HTPC_Setups.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Handheld_PCs.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Steam_Deck.md
  docs/src/General/Installation_Guide/dual_boot_setup_guide.md
  docs/src/General/Installation_Guide/index.md
  docs/src/General/Installation_Guide/secure_boot.md
  docs/src/General/Installation_Guide/troubleshoot_guide.md
  docs/src/General/reporting_bugs.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Other_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
  docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
  docs/src/Installing_and_Managing_Software/AppImage.md
  docs/src/Installing_and_Managing_Software/Distrobox.md
  docs/src/Installing_and_Managing_Software/Flatpak.md
  docs/src/Installing_and_Managing_Software/Homebrew.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/bazzite_rollback_helper.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/index.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/rebase_guide.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/rolling_back_system_updates.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/updating_guide.md
  docs/src/Installing_and_Managing_Software/Waydroid_Setup_Guide.md
  docs/src/Installing_and_Managing_Software/index.md
  docs/src/Installing_and_Managing_Software/rpm-ostree.md
  docs/src/Installing_and_Managing_Software/ujust.md
  docs/url_overrides.yml
  docs/utils/benchmark.sh
  docs/utils/fetch_discourse_md.py
  docs/utils/transcribe.py
Labels: documentation, size:XXL, lgtm

#1612 chore(docs): Fix issues with ujust documentation
  docs/src/Installing_and_Managing_Software/ujust.md
Labels: documentation, size:XS, lgtm

#1614 chore(docs): Last change to warning
  docs/theme_overrides/main.html
Labels: documentation, size:XS, lgtm

#1620 chore(docs): Add a shortcut for auto-mounting drives
  docs/src/Gaming/Game_Launchers.md
Labels: documentation, size:XS, lgtm

#1621 chore(docs): Fix broken links in auto-mount guide
  docs/src/Advanced/Auto-Mounting_Secondary_Drives.md
Labels: documentation, size:XS, lgtm

#1613 chore(docs): Handheld Wiki can be edited properly
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
Labels: documentation, size:S, lgtm

#1617 chore(readme): Remove references to Newsletters
  README.md
Labels: documentation, size:S, lgtm

#1624 docs: Replace discourse URLs with local ones
  docs/mkdocs.yml
  docs/src/Advanced/Auto-Mounting_Secondary_Drives.md
  docs/src/Advanced/Contributing_to_bazzite.md
  docs/src/Gaming/Common_gaming_issues.md
  docs/src/Gaming/Game_Launchers.md
  docs/src/Gaming/Hardware_compatibility_for_gaming.md
  docs/src/Gaming/Managing_and_modding_games.md
  docs/src/Gaming/index.md
  docs/src/General/Contributing_to_Bazzite.md
  docs/src/General/Desktop_Environment_Tweaks.md
  docs/src/General/FAQ.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_HTPC_Setups.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Handheld_PCs.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Steam_Deck.md
  docs/src/General/Installation_Guide/dual_boot_setup_guide.md
  docs/src/General/Installation_Guide/index.md
  docs/src/General/reporting_bugs.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Other_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
  docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
  docs/src/Installing_and_Managing_Software/AppImage.md
  docs/src/Installing_and_Managing_Software/Distrobox.md
  docs/src/Installing_and_Managing_Software/Flatpak.md
  docs/src/Installing_and_Managing_Software/Homebrew.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/bazzite_rollback_helper.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/index.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rebase_guide.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rolling_back_system_updates.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/updating_guide.md
  docs/src/Installing_and_Managing_Software/Waydroid_Setup_Guide.md
  docs/src/Installing_and_Managing_Software/index.md
  docs/src/Installing_and_Managing_Software/rpm-ostree.md
  docs/src/Installing_and_Managing_Software/ujust.md
  docs/src/stylesheets/bazzite.css
  docs/theme_overrides/main.html
Labels: documentation, size:L, lgtm

#1627 chore(readme): fix updates, rollback, and rebasing link
  README.md
Labels: documentation, size:XS, lgtm

#1626 fix(documentation): fix screen overclocking variable and values
  README.md
Labels: documentation, steam-deck, size:XS, lgtm

#1629 chore(readme): Add ujust install-resolve to the list of features
  README.md
Labels: documentation, size:XS, lgtm

#1630 chore(motd): Update to new documentation
  system_files/desktop/shared/usr/share/ublue-os/motd/tips/10-ublue.md
  system_files/desktop/shared/usr/share/ublue-os/motd/tips/20-bazzite.md
Labels: documentation, size:XS, lgtm

#1636 feat: add support for onexfly 8840U
  system_files/deck/kinoite/usr/libexec/hardware/needs-left-rotation
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
  system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Labels: enhancement, size:S, lgtm

#1637 chore(just): Improve wording in install-resolve prompts
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: documentation, size:XS, lgtm

#1648 chore(docs): Documentation Documentation Fix?
  docs/README.md
Labels: documentation, size:M, lgtm

#1651 chore(docs): Update outdated info in docs related to Decky
  docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
Labels: documentation, size:XS, lgtm

#1646 chore(docs): New announcement for documentation
  docs/theme_overrides/main.html
Labels: documentation, size:XS, lgtm

#1645 chore(docs): Handheld Wiki Updates
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
Labels: documentation, size:L, lgtm

#1644 chore(docs): Distrobox Edits
  docs/src/Installing_and_Managing_Software/Distrobox.md
Labels: documentation, size:S, lgtm

#1647 chore(docs): Final strides
  docs/src/Advanced/Contributing_to_bazzite.md
  docs/src/Advanced/Reset_Forgotten_User_Password.md
  docs/src/Advanced/creating_custom_image.md
  docs/src/Gaming/Common_gaming_issues.md
  docs/src/Gaming/Managing_and_modding_games.md
  docs/src/General/Installation_Guide/dual_boot_setup_guide.md
  docs/src/General/reporting_bugs.md
  docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
  docs/src/Installing_and_Managing_Software/Homebrew.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rolling_back_system_updates.md
  docs/src/Installing_and_Managing_Software/ujust.md
Labels: documentation, size:M, lgtm

#1655 chore(docs): fix links to updates rollback and rebasing
  docs/src/index.md
Labels: documentation, size:S, lgtm

#1656 chore(docs): Fix contributing guide (again)
  docs/src/General/Contributing_to_Bazzite.md
Labels: documentation, size:S, lgtm

#1652 chore(docs): update GPD documentation
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
Labels: documentation, size:M, lgtm

#1653 chore(docs): Link installation guide in Steam Deck wiki
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
Labels: documentation, steam-deck, size:S, lgtm

#1659 docs: Fix several pages with broken headers and other fixes
  docs/Justfile
  docs/mkdocs.yml
  docs/src/Advanced/Auto-Mounting_Secondary_Drives.md
  docs/src/Advanced/Contributing_to_bazzite.md
  docs/src/Advanced/GNOME_Disks_Auto-Mount_Guide.md
  docs/src/Advanced/KDE_Partition_Manager_Auto_Mount_Guide.md
  docs/src/Advanced/Reset_Forgotten_User_Password.md
  docs/src/Advanced/creating_custom_image.md
  docs/src/Gaming/Common_gaming_issues.md
  docs/src/Gaming/Game_Launchers.md
  docs/src/Gaming/Hardware_compatibility_for_gaming.md
  docs/src/Gaming/Managing_and_modding_games.md
  docs/src/Gaming/index.md
  docs/src/General/Contributing_to_Bazzite.md
  docs/src/General/Desktop_Environment_Tweaks.md
  docs/src/General/FAQ.md
  docs/src/General/Installation_Guide/Installing_Bazzite_Framework_Laptop_13.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Desktop_or_Laptop_Hardware.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Framework_Laptop_16.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_HTPC_Setups.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Handheld_PCs.md
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Steam_Deck.md
  docs/src/General/Installation_Guide/dual_boot_setup_guide.md
  docs/src/General/Installation_Guide/index.md
  docs/src/General/Installation_Guide/secure_boot.md
  docs/src/General/Installation_Guide/troubleshoot_guide.md
  docs/src/General/reporting_bugs.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Other_Handhelds.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
  docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
  docs/src/Installing_and_Managing_Software/AppImage.md
  docs/src/Installing_and_Managing_Software/Distrobox.md
  docs/src/Installing_and_Managing_Software/Flatpak.md
  docs/src/Installing_and_Managing_Software/Homebrew.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/bazzite_rollback_helper.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/index.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rebase_guide.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rolling_back_system_updates.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/updating_guide.md
  docs/src/Installing_and_Managing_Software/Waydroid_Setup_Guide.md
  docs/src/Installing_and_Managing_Software/index.md
  docs/src/Installing_and_Managing_Software/rpm-ostree.md
  docs/src/Installing_and_Managing_Software/ujust.md
  docs/src/index.md
  docs/src/stylesheets/bazzite.css
  docs/theme_overrides/main.html
  docs/utils/install-deps.sh
Labels: documentation, size:XXL, lgtm

#1662 chore(docs): Fixing update doc 404 for real this time
  docs/src/index.md
Labels: documentation, size:XS, lgtm

#1658 chore(docs): Update README-BR in line with 3.7.0
  README-BR.md
Labels: documentation, size:M, lgtm

#1660 chore(docs): Capital B for bazzite
  docs/src/index.md
Labels: documentation, size:XS, lgtm

#1666 chore(docs): No more numbered steps for update docs
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/updating_guide.md
Labels: documentation, size:XS, lgtm

#1664 chore(docs): Give AppImage a description
  docs/src/index.md
Labels: documentation, size:S, lgtm

#1665 chore(docs): Steam Deck FAQ link fix
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
Labels: documentation, steam-deck, size:XS, lgtm

#1663 docs: steam deck oled no longer requires basic graphics mode
  docs/src/General/Installation_Guide/Installing_Bazzite_for_Steam_Deck.md
Labels: documentation, steam-deck, size:XS, lgtm

#1671 ci: Remove docs dir placeholder before cloning docs repo
  .github/workflows/build.yml
Labels: size:XS, lgtm

#1674 feat(ujust): add ujust for ryzenadj --max-performance
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: enhancement, size:S, lgtm

#1684 chore(motd): Link new documentation
  system_files/desktop/kinoite/usr/share/ublue-os/motd/tips/30-kde.md
Labels: documentation, size:XS, lgtm

#1683 chore: Replace Discourse link with new docs page
  system_files/desktop/shared/usr/bin/waydroid-launcher
Labels: documentation, size:XS, lgtm

#1682 feat(just): Link new documentation
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-waydroid.just
Labels: documentation, size:XS, lgtm

#1693 fix: btrfs-dedup don't wait on compsize since compsize doesn't run
  system_files/desktop/shared/usr/bin/btrfs-dedup
Labels: bug, size:XS, lgtm

#1685 fix(deck): update just recipe to infer DeckHD bios install
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: bug, steam-deck, size:XS, lgtm

#1712 chore: remove framework akmod install
  Containerfile
Labels: size:XS, lgtm
