Repository ublue-os/bazzite, pull requests merged in 2024-10, with the labels that each got.

#1705 chore: add warning text for invalid args to bazzite-rollback-helper
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: size:XS, lgtm

#1713 feat(bazzite-cli): add trash-cli
  system_files/overrides/usr/share/ublue-os/homebrew/bazzite-cli.Brewfile
Labels: enhancement, size:XS, lgtm

#1724 fix(deck): Use super + 1/2 for Overlay/QAM
  spec_files/gamescope/gamescope-legacy.spec
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/v2-0001-always-send-ctrl-1-2-to-steam-s-wayland-session.patch
  spec_files/gamescope/v2-0001-steam-overlay-hotkeys.patch
  system_files/deck/shared/etc/environment
Labels: steam-deck, size:M, lgtm

#1723 chore(readme): Use the "resources" doc over the Discourse link
  README.md
Labels: documentation, size:XS

#1743 chore(hhd): add OneXPlayer, Ayaneo, and GPD to hhd supported devices
  system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Labels: enhancement, size:XS

#1737 chore: Cleanup version information to be more intuitive
  .github/workflows/build.yml
  system_files/desktop/shared/usr/libexec/containerbuild/image-info
Labels: size:S, lgtm

#1736 feat(gamescope): prepare to start tracking upstream + cleanup
  spec_files/gamescope/0002-limits.patch
  spec_files/gamescope/ally-display.patch
  spec_files/gamescope/chimeraos-cleanup-v1.patch
  spec_files/gamescope/chimeraos.patch
  spec_files/gamescope/disable-steam-touch-click-atom.patch
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/legacy-720p.patch
  spec_files/gamescope/v2-0001-steam-overlay-hotkeys.patch
Labels: upstream, size:XXL, lgtm

#1745 fix(legion go): remove lcd script
  system_files/deck/shared/usr/share/gamescope/scripts/00-gamescope/displays/lenovo.legiongo.lcd.lua
Labels: size:M, lgtm

#1740 feat(ally x): add convolver for Ally X
  system_files/deck/shared/usr/share/pipewire/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/Cor1S48.wav
  system_files/deck/shared/usr/share/pipewire/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/pipewire.conf.d/filter-chain.conf
Labels: enhancement, size:M, lgtm

#1754 fix(steam): Add shortcut to start Steam BPM without slugishness
  Containerfile
  system_files/deck/shared/usr/share/gamescope/scripts/00-gamescope/displays/lenovo.legiongo.lcd.lua
  system_files/desktop/shared/usr/bin/bazzite-steam-bpm
  system_files/desktop/shared/usr/share/applications/bazzite-steam-bpm.desktop
Labels: bug, size:M, lgtm

#1766 chore: remove sudo from bazzite setup script
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Labels: size:S

#1765 feat(ujust): add pwfeedback toggle
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: enhancement, size:S

#1768 feat: update gamescope patches with new features
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: enhancement, size:L

#1775 chore: update f41 pipewire to version 1.2.6
  spec_files/pipewire/pipewire.spec
Labels: size:M

#1771 fix: temporarily disable "turn off screen when idle" in kde for handhelds
  system_files/deck/shared/usr/bin/bazzite-desktop-bootstrap
Labels: bug, size:XS

#1767 feat: add automatically generated changelogs
  .github/workflows/build.yml
  .github/workflows/changelog.py
  .github/workflows/generate_release.yml
Labels: enhancement, size:L

#1777 fix: fix VRR disable in SteamUI to work correctly
  spec_files/gamescope/handheld.patch
Labels: bug, size:L, lgtm

#1780 fix(changelogs): Fix changelog ref error
  .github/workflows/changelog.py
Labels: bug, size:S

#1779 chore: Remove rechunk compression and spurious tags
  .github/workflows/build.yml
Labels: size:S

#1459 feat: Add btrfs-assistant to easily configure automatic snapshots of /home
  Containerfile
  system_files/desktop/shared/usr/lib/systemd/system/bazzite-snapper-setup.service
  system_files/desktop/shared/usr/libexec/bazzite-snapper-setup
  system_files/desktop/shared/usr/share/snapper/config-templates/default
Labels: enhancement, size:M

#1782 fix: fix version number in changelogs
  .github/workflows/changelog.py
Labels: bug, size:XS, lgtm

#1784 fix(selinux): fix setroubleshoot stacktraces
  Containerfile
Labels: bug, size:XS

#1786 chore(changelog): Tweak changelog with rebase command, ignore refs in target
  .github/workflows/changelog.py
  .github/workflows/generate_release.yml
Labels: size:S, lgtm

#1789 feat(ujust): Update pwfeedback ujust to include optional arg
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: enhancement, size:S, lgtm

#1788 chore: Replace old documentation link for ujust
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: documentation, size:XS, lgtm

#1791 chore: Rewrite of bazzite-rollback-helper and shorter name
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
  system_files/desktop/shared/usr/bin/brh
Labels: size:XS

#1793 Controverisal and opinionated Bazzite Portal changes
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:L

#1792 feat(just): add ujust for installing speaker firmware
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: enhancement, size:S

#1794 Fix issues with Bazzite Portal for Desktop images
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:S

#1795 chore(ujust): Fix -deck version of yafti configuration
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:S

#1806 fix(changelogs): change main to stable
  .github/workflows/generate_release.yml
Labels: size:XS

#1805 chore(bazzite-rollback-helper): Minor tweaks
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: size:XS

#1813 chore(yafti): Fix order for deck configuration
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:S

#1812 chore(yafti): Add visible password to desktop yaml config
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:XS

#1811 fix(gamescope): improve SteamUI refresh halving
  spec_files/gamescope/handheld.patch
Labels: bug, size:L

#1814 feat: add_evdi back for F41
  Containerfile
Labels: enhancement, size:XS

#1778 chore: Reorder the build steps to save time and image size
  .github/workflows/build.yml
Labels: size:M, lgtm

#1819 feat: Replace copr utility with dnf5 copr wrapper
  Containerfile
  system_files/desktop/shared/usr/bin/copr
Labels: enhancement, size:XS

#1821 fix: add sudo to secureboot check
  .github/workflows/build.yml
Labels: bug, size:XS

#1822 linuZ + rechunk bump
  .github/workflows/build.yml
Labels: size:XS

#1823 fix: add signing tag so that signing works
  .github/workflows/build.yml
Labels: size:XS

#1828 fix: fixup build action signing
  .github/workflows/build.yml
Labels: size:XS

#1832 fix: fixup image perms to work with rootless podman
  .github/workflows/build.yml
Labels: size:XS

#1833 fix: use proper var for output image location
  .github/workflows/build.yml
Labels: size:XS

#1834 fix: give up and revert to root again
  .github/workflows/build.yml
Labels: size:XS

#1835 fix: use digest for image signing instead
  .github/workflows/build.yml
Labels: size:XS
