Repository ublue-os/bazzite, pull requests merged in 2024-07, with the labels that each got.

#1314 refactor: update cosign public key
  cosign.pub
Labels: size:XS, lgtm

#1310 chore: Remove Documentation shortcut and replace Landing icon
  system_files/desktop/shared/usr/share/applications/bazzite-documentation.desktop
  system_files/desktop/shared/usr/share/applications/bazzite-landing.desktop
  system_files/desktop/shared/usr/share/ublue-os/bazzite/Landing.svg
  system_files/desktop/shared/usr/share/ublue-os/bazzite/docs.svg
  system_files/desktop/shared/usr/share/ublue-os/bazzite/welcome.svg
Labels: documentation, size:S, lgtm

#1303 chore: Update README-BR in line with 3.5.0
  README-BR.md
Labels: documentation, size:S, lgtm

#1336 feat(ujust): Add install-resolve
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: enhancement, size:M, lgtm

#1337 feat: Container indicator for fish shell
  system_files/overrides/usr/share/fish/functions/fish_prompt.fish
Labels: enhancement, size:M, lgtm

#1342 fix(ujust): Fix faulty ujust install-resolve
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: bug, size:S, lgtm

#1351 fix(gpd) don't rotate GPU Win Mini 2024 7640U display
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Labels: bug, size:XS, lgtm

#1364 feat: Add offline documentation (markdown version)
  system_files/desktop/shared/usr/share/applications/Documentation.desktop
  system_files/desktop/shared/usr/share/applications/bazzite-landing.desktop
  system_files/desktop/shared/usr/share/ublue-os/bazzite/Landing.svg
  system_files/desktop/shared/usr/share/ublue-os/bazzite/docs.svg
  system_files/desktop/shared/usr/share/ublue-os/docs/Bazzite Landing.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Common Gaming Issues.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Game Launchers.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Hardware Compatibility.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Linux Gaming Resources.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Managing and Modding Games.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite FAQ.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite README.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite and SteamOS Comparison.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Desktop Environment Tweaks.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Reset User Password.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Secure Boot Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/ASUS ROG Ally.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Ayaneo Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Ayn Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/GPD Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/General Handheld Information.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Lenovo Legion Go.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Other Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Steam Deck.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Steam Gaming Mode/Steam Gaming Mode Common Issues.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Steam Gaming Mode/Steam Gaming Mode Overview.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/AppImage.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Distrobox.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Flatpak.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Homebrew.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Steam Gaming Mode Overview.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Waydroid Setup Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Windows Applications.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/rpm-ostree.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/ujust.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/Rebasing Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/System Rollbacks.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/Updating Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/bazzite-rollback-helper.md
Labels: documentation, size:XXL, lgtm

#1367 feat: Install `wqy-zenhei-fonts` for GoldSrc engine to display Chinese fonts
  Containerfile
Labels: enhancement, size:XS, lgtm

#1370 chore(docs): Fix README offline doc
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite README.md
Labels: documentation, size:S, lgtm

#1371 fix(ujust): set install as the default action for the setup-decky ujust
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: bug, size:XS, lgtm

#1372 chore(docs): Remove experimental audio note
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Lenovo Legion Go.md
Labels: documentation, size:XS

#1378 chore(readme): Remove outdated `-deck` information
  README-BR.md
  README-FR.md
  README-NL.md
  README-SPA.md
  README-zh-cn.md
  README.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/System Rollbacks.md
Labels: documentation, size:M, lgtm

#1386 chore(ci): Check Kernel is signed for Secureboot
  .github/workflows/build.yml
Labels: size:M, lgtm

#1389 chore(docs): Add information on undoing...
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Common Gaming Issues.md
Labels: documentation, size:S, lgtm

#1320 chore(ci): add a workflow to manually sign an image with Cosign
  .github/workflows/sign_image.yml
Labels: enhancement, size:M, lgtm

#1388 chore(ci): use cache-mount and bind mounts
  Containerfile
  system_files/desktop/shared/usr/libexec/containerbuild/cleanup.sh
Labels: size:L, lgtm

#1396 fix(Ally X): disable MCU powersave
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Labels: bug, size:XS

#1392 chore(docs): Updated GPD Win Max 2 information
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/GPD Handhelds.md
Labels: documentation, size:S, lgtm

#1399 feat(kde): add fcitx5-hangul for Korean input
  Containerfile
Labels: enhancement, size:XS, lgtm

#1401 Revert: chore: Fixed upstream
  Containerfile
Labels: size:XS, lgtm

#1411 feat(just): add ujust to reset steam
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
Labels: enhancement, size:S, lgtm

#1403 feat: Add Discourse forums shortcut
  system_files/desktop/shared/usr/share/applications/discourse.desktop
  system_files/desktop/shared/usr/share/ublue-os/bazzite/discourse.svg
Labels: enhancement, size:XS, lgtm

#1424 feat(just) Add bazzite - cli bling for issue #1385
  Containerfile
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
  system_files/overrides/usr/share/bazzite-cli/bling.fish
  system_files/overrides/usr/share/bazzite-cli/bling.sh
  system_files/overrides/usr/share/ublue-os/homebrew/bazzite-cli.Brewfile
Labels: enhancement, size:L, lgtm

#1425 feat(just): add decky prerelease option
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, steam-deck, size:S, lgtm

#1432 fix: topgrade typo
  system_files/desktop/shared/usr/share/ublue-os/topgrade.toml
Labels: bug, size:XS, lgtm

#1436 fix(LGO): fix audio input and output priorities for Legion Go
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/lenovo-83e1/wireplumber.conf.d/51-preferHDMI.conf
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/lenovo-83e1/wireplumber.conf.d/60-raise-internal-mic.conf
Labels: bug, steam-deck, size:M, lgtm

#1439 feat(rechunk): Introduce image rechunking to lower update sizes
  .github/workflows/build.yml
Labels: enhancement, size:L, lgtm

#1443 feat(rechunk): enable previous layer checks and bump version
  .github/workflows/build.yml
Labels: enhancement, size:S
