Repository ublue-os/bazzite, pull requests merged in 2024-11, with the labels that each got.

#1840 feat: Add atom for controlling refresh rate halving in Steam
  spec_files/gamescope/handheld.patch
  system_files/deck/shared/usr/lib/systemd/system/hhd@.service.d/override.conf
Labels: enhancement, size:L

#1841 chore(yafti): Fix syntax error
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:S

#1859 fix: typo in copr wrapper
  system_files/desktop/shared/usr/bin/copr
Labels: bug, size:XS, lgtm

#1742 chore: gate stable and add promotion action
  .github/workflows/build.yml
  .github/workflows/promote.yml
Labels: size:M, lgtm

#1853 chore(yafti): Remove Oversteer (-deck Edition)
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:S, lgtm

#1852 chore(yafti): Remove Oversteer (Desktop Edition)
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:XS, lgtm

#1838 feat(just): Update surround to use spatializer
  system_files/desktop/shared/usr/share/ublue-os/just/83-bazzite-audio.just
Labels: enhancement, size:L, lgtm

#1848 feat(ujust): Add setup-boot-windows-steam ujust script
  Containerfile
  system_files/desktop/shared/usr/bin/boot-windows
  system_files/desktop/shared/usr/share/ublue-os/just/86-bazzite-windows.just
Labels: enhancement, size:XS, lgtm

#1863 fix(bazzite-steam): correctly add the HHD steam controller on non valve hardware
  system_files/desktop/shared/usr/bin/bazzite-steam
Labels: bug, size:XS, lgtm

#1881 fix: source LACT from copr instead of downloading from releases page
  Containerfile
  system_files/desktop/shared/etc/ublue-os/topgrade.toml
  system_files/desktop/shared/usr/libexec/topgrade/lact-update
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: size:M, lgtm

#1885 Add protontricks-launch to run .exes via commandline
  system_files/desktop/shared/usr/bin/protontricks-launch
Labels: enhancement, size:XS, lgtm

#1880 fix: prevent partial pushes causing partial changelogs
  .github/workflows/changelog.py
Labels: bug, size:S, lgtm

#1879 fix(just): add toggle-password-feedback to all images
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: size:M

#1878 feat(just): Improve install speaker firmware
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: enhancement, size:S

#1876 feat: add DPMS support to gamescope + disable 60hz by default
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: enhancement, size:L, lgtm

#1886 fix(gamescope): force dpms even if steamui is not blanking
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: bug, size:M, lgtm

#1887 fix: reinstate ujust install-lact karg modification
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: bug, size:XS, lgtm

#1894 feat(hhd): add env vars for new features
  system_files/deck/shared/usr/lib/systemd/system/hhd@.service.d/override.conf
Labels: enhancement, size:XS

#1898 fix(yafti): Fix Bazzite Portal not launching on -deck images
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: bug, steam-deck, size:S

#1901 fix: chmod +x protontricks-launch
  system_files/desktop/shared/usr/bin/protontricks-launch
Labels: bug, size:XS

#1911 chore(yafti): Apply changes from -deck to desktop
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/bin/protontricks-launch
Labels: size:S, lgtm

#1926 fix(sddm): Create sddm themes overlay directories
  system_files/desktop/kinoite/usr/lib/systemd/system/usr-share-sddm-themes.mount
  system_files/desktop/kinoite/usr/lib/tmpfiles.d/usr-share-sddm-themes.conf
Labels: size:S

#1922 feat(ci): clean up images older than 90 days
  .github/workflows/clean.yml
Labels: enhancement, size:S

#1931 fix(yafti): Install More Applications button not opening gnome-software in bazzite-gnome
  .github/workflows/build.yml
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: bug, size:XS
