Repository ublue-os/bazzite, pull requests merged in 2024-12, with the labels that each got.

#1948 fix(tuned-ppd): correct config existence check in bazzite-hardware-setup
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Labels: bug, size:XS

#1946 feat(hhd): enable bootc support
  system_files/deck/shared/usr/lib/systemd/system/hhd@.service.d/override.conf
Labels: enhancement, size:XS

#1934 chore: Note about rebasing between DEs with brh
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: size:XS, lgtm

#1955 chore(readme): Remove outdated kf5-kio listing
  README-SPA.md
Labels: documentation, size:XS

#1939 fix: remove default snapper config and incorrect snapshots
  Containerfile
  system_files/desktop/shared/usr/lib/systemd/system/bazzite-snapper-setup.service
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
  system_files/desktop/shared/usr/libexec/bazzite-snapper-setup
  system_files/desktop/shared/usr/share/snapper/config-templates/default
Labels: bug, size:L, lgtm

#1956 feat(gamescope: add X1 intel rotation and change versioning format
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: enhancement, size:XL

#1958 fix(mesa): add temporary patch for Indiana Jones and the Great Circle
  spec_files/mesa/indiana.patch
  spec_files/mesa/mesa.spec
Labels: bug, size:L

#1968 feat(hhd): apply with fallback hhd bootc updater to steam
  system_files/deck/shared/usr/bin/steamos-update
  system_files/deck/shared/usr/libexec/os-branch-select
Labels: steam-deck, size:S, lgtm

#1967 feat(hhd): add bug reporting tool
  system_files/deck/shared/usr/lib/systemd/system/hhd@.service.d/override.conf
Labels: enhancement, size:XS, lgtm

#1970 fix(hhd): use absolute path to find update executable
  system_files/deck/shared/usr/bin/steamos-update
  system_files/deck/shared/usr/libexec/os-branch-select
Labels: bug, size:XS

#1973 fix: fix trailing commas in JSON
  system_files/desktop/shared/usr/share/ublue-os/motd/themes/pink.json
  system_files/desktop/shared/usr/share/ublue-os/motd/themes/purple.json
  system_files/desktop/shared/usr/share/ublue-os/motd/themes/red.json
Labels: bug, size:XS, lgtm

#1977 fix: remove static links from build_iso workflow
  .github/workflows/build_iso.yml
Labels: iso, size:S, lgtm

#1978 fix: split image registry variable in build workflow
  .github/workflows/build.yml
Labels: size:S, lgtm

#1999 fix(waydroid): Relabel /var/lib/waydroid on initial setup
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-waydroid.just
Labels: bug, size:XS, lgtm

#1991 feat(deck): Smart video handling, allow configuring.
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
  system_files/desktop/shared/usr/bin/bazzite-steam
Labels: enhancement, steam-deck, size:M, lgtm

#2005 fix(mesa): re-backport indiana jones patches for 24.2.8
  spec_files/mesa/indiana-2.patch
  spec_files/mesa/mesa.spec
Labels: bug, size:L

#2004 fix: workaround for motd messing up midnight commander subshell, issue #2003
  system_files/desktop/shared/usr/libexec/ublue-motd
Labels: bug, size:XS

#2000 fix: Adjust yafti and sunshine ujust for layered version of sunshine
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-sunshine.just
Labels: size:M, lgtm

#2018 fix(ujust): removed removed script dependencies for ujust setup-boot-windows-steam
  system_files/desktop/shared/usr/share/ublue-os/just/86-bazzite-windows.just
Labels: bug, size:XS

#2019 fix: return on bling.sh if it already got sourced
  system_files/overrides/usr/share/bazzite-cli/bling.sh
Labels: bug, size:XS, lgtm

#2023 fix: update ArtifactHub README.md
  .github/workflows/build.yml
Labels: bug, size:XS

#2024 feat: add ls-iommu and update virtualization ujust for bootc transition
  Containerfile
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: enhancement, size:M, lgtm

#2037 fix(yafti): fix yafti pwfeedback toggle
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: bug, size:XS, lgtm
