Repository ublue-os/bazzite, pull requests merged in 2024-08, with the labels that each got.

#1446 fix: Prevent bluetooth preventing suspension
  system_files/desktop/shared/usr/lib/systemd/system/bluetooth.service.d/prevent_hanging.conf
Labels: bug, size:XS, lgtm

#1442 feat: standardize versioning across OSTree and os-release
  .github/workflows/build.yml
  Containerfile
  system_files/desktop/shared/usr/libexec/containerbuild/image-info
Labels: enhancement, size:L, lgtm

#1450 feat: Add ujust command for stress-ng benchmark
  Containerfile
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:XS, lgtm

#1451 fix(just): fix syntax for benchmark ujust
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: bug, size:XS, lgtm

#1452 fix(LGO): reduce input source priority and add description
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/lenovo-83e1/wireplumber.conf.d/60-raise-internal-mic.conf
Labels: bug, size:XS, lgtm

#1460 feat(bazzite-cli): add tealdeer as tldr
  system_files/overrides/usr/share/ublue-os/homebrew/bazzite-cli.Brewfile
Labels: enhancement, size:XS, lgtm

#1467 fix(Ally X): prefer HDMI audio when docked
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/51-preferHDMI.conf
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/alsa-card0.conf
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/alsa-card1.conf
Labels: steam-deck, size:M, lgtm

#1468 fix(nvidia): pin Nvidia drivers to 555
  Containerfile
Labels: bug, size:XS, lgtm

#1494 feat(cli): Alias `xdg-open` to `open`
  system_files/desktop/shared/etc/profile.d/open.sh
Labels: enhancement, size:XS, lgtm

#1428 feat(nvidia): add script check for legacy nvidia hardware
  system_files/nvidia/shared/usr/libexec/nvidia-legacy-hardware
Labels: enhancement, size:XS, lgtm

#1503 fix: update bazzite-rollback-helper list to capture new image tags
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: bug, size:XS, lgtm

#1509 fix(rechunk): use correct previous ref
  .github/workflows/build.yml
Labels: bug, size:XS, lgtm

#1508 feat: allow external scripts to specify nested-desktop/waydroid dimensions
  spec_files/steamdeck-kde-presets/nested-desktop-resolution.patch
  system_files/desktop/shared/usr/bin/waydroid-launcher
  system_files/desktop/shared/usr/libexec/waydroid-container-start
Labels: enhancement, steam-deck, size:S, lgtm

#1483 feat(fish): enhanced fish performance
  system_files/overrides/usr/share/fish/vendor_conf.d/brew.fish
Labels: bug, size:S, lgtm

#1521 chore(docs): Delete offline documentation temporarily...
  system_files/desktop/shared/usr/share/applications/bazzite-documentation.desktop
  system_files/desktop/shared/usr/share/ublue-os/bazzite/docs.svg
  system_files/desktop/shared/usr/share/ublue-os/docs/Bazzite Landing.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Common Gaming Issues.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Game Launchers.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Hardware Compatibility.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Linux Gaming Resources.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Gaming/Managing and Modding Games.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite FAQ.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite README.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Bazzite and SteamOS Comparison.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Desktop Environment Tweaks.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Reset User Password.md
  system_files/desktop/shared/usr/share/ublue-os/docs/General/Secure Boot Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/ASUS ROG Ally.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Ayaneo Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Ayn Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/GPD Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/General Handheld Information.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Lenovo Legion Go.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Other Handhelds.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Handheld Wiki/Steam Deck.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Steam Gaming Mode/Steam Gaming Mode Common Issues.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Handheld and HTPC Edition/Steam Gaming Mode/Steam Gaming Mode Overview.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/AppImage.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Distrobox.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Flatpak.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Homebrew.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Steam Gaming Mode Overview.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Waydroid Setup Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/Windows Applications.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/rpm-ostree.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Installing and Managing Applications/ujust.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/Rebasing Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/System Rollbacks.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/Updating Guide.md
  system_files/desktop/shared/usr/share/ublue-os/docs/Updates Rollbacks and Rebasing/bazzite-rollback-helper.md
Labels: documentation, size:XXL, lgtm

#1533 feat(ujust): add post-gamescope-logs ujust
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:M, lgtm

#1530 feat: Add offline documentation
  .github/workflows/build.yml
  system_files/desktop/shared/usr/share/applications/bazzite-documentation.desktop
  system_files/desktop/shared/usr/share/ublue-os/bazzite/docs.svg
Labels: documentation, size:S, lgtm

#1549 fix(just): add libvirt package to setup-virtualization
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: upstream, size:S, lgtm

#1540 chore: minor updates to help text for bazzite-rollback-helper
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: documentation, size:XS, lgtm

#1545 docs: Add new doc pages
  docs/src/Advanced/creating_custom_image.md
  docs/src/Bazzite_resources.md
  docs/src/Gaming/Common_gaming_issues.md
  docs/src/Gaming/Hardware_compatibility_for_gaming.md
  docs/src/Gaming/Managing_and_modding_games.md
  docs/src/General/Installation_Guide/dual_boot_setup_guide.md
  docs/src/General/Installation_Guide/secure_boot.md
  docs/src/General/Installation_Guide/troubleshoot_guide.md
  docs/src/General/reporting_bugs.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/bazzite_rollback_helper.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/index.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/rebase_guide.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/rolling_back_system_updates.md
  docs/src/Installing_and_Managing_Software/Updates_Rollbacks_&_Rebasing/updating_guide.md
  docs/src/SUMMARY.md
  docs/utils/fetch_discourse_md.py
Labels: documentation, size:L, lgtm

#1551 chore(docs): Delete Bazzite Resources
  docs/src/Bazzite_resources.md
Labels: documentation, size:XS, lgtm

#1557 chore(docs): Shorten Steam Gaming Mode docs header
  docs/src/SUMMARY.md
Labels: documentation, size:XS, lgtm

#1558 chore(docs): Fix broken Hardware Compat. Documentation
  docs/src/Gaming/Hardware_compatibility_for_gaming.md
Labels: documentation, size:XS, lgtm

#1556 chore(docs): Delete Physical Keyboard Layout
  docs/src/Handheld_and_HTPC_edition/Change_Physical_Keyboard_Layout_for_Steam_Gaming_Mode.md
  docs/src/SUMMARY.md
Labels: documentation, size:XS, lgtm

#1560 chore(docs): Add 'Fork An Image' Documentation
  docs/src/SUMMARY.md
Labels: documentation, size:XS, lgtm

#1561 chore(docs): add new page
  docs/src/SUMMARY.md
Labels: documentation, size:XS, lgtm

#1550 feat: Remove Konsole & GNOME Terminal to save space in-image
  Containerfile
  README.md
Labels: documentation, enhancement, size:XS, lgtm

#1548 feat(docs): Replace mdbook with mkdocs workflow
  .github/workflows/build.yml
  .github/workflows/build_mkdocs/action.yml
  .github/workflows/deploy_docs.yml
  .github/workflows/install-mdbook/action.yml
  docs/.gitignore
  docs/Justfile
  docs/README.md
  docs/book.toml
  docs/custom.css
  docs/hooks/cmdrun.py
  docs/hooks/embed_youtube.py
  docs/hooks/fetch_discourse_md.py
  docs/mkdocs.yml
  docs/poetry.lock
  docs/preprocessors/format-author.py
  docs/preprocessors/libs/__init__.py
  docs/preprocessors/libs/git.py
  docs/preprocessors/libs/types.py
  docs/preprocessors/libs/utils.py
  docs/preprocessors/preprocessor-example.py
  docs/preprocessors/replace-urls.py
  docs/preprocessors/youtube-embed.py
  docs/pyproject.toml
  docs/src/Gaming/index.md
  docs/src/General/FAQ.md
  docs/src/General/Installation_Guide/index.md
  docs/src/Handheld_and_HTPC_edition/Handheld_Wiki/index.md
  docs/src/Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
  docs/src/Introduction.md
  docs/src/img/doc_guide_add_summary.jpg
  docs/src/img/doc_guide_where_did_go.jpg
  docs/src/img/favicon.png
  docs/src/img/favicon.svg
  docs/src/img/logo_BW.svg
  docs/src/index.md
  docs/src/stylesheets/image_sizing.css
  docs/theme/index.hbs
  docs/theme_overrides/main.html
  docs/utils/fetch_discourse_md.py
  docs/utils/install-deps.sh
  system_files/desktop/shared/usr/share/applications/bazzite-documentation.desktop
  system_files/desktop/shared/usr/share/ublue-os/docs/serve.sh
Labels: documentation, size:XXL, lgtm

#1568 ci(docs): Add retry logic to build_mkdocs
  .github/workflows/build_mkdocs/action.yml
Labels: documentation, size:S, lgtm

#1576 docs: Hide 'Auto-Mounting Secondary Drives' article
  docs/mkdocs.yml
  docs/src/index.md
Labels: documentation, size:XS, lgtm

#1571 fix(docs): Several fixes for mkdocs
  docs/hooks/embed_youtube.py
  docs/hooks/md_image_sizing.py
  docs/mkdocs.yml
  docs/utils/fetch_discourse_md.py
Labels: documentation, size:M, lgtm

#1575 chore(docs): Fix note at the top
  docs/theme_overrides/main.html
Labels: documentation, size:XS, lgtm

#1584 fix(docs): Use a working match substitution in md_image_sizing hook
  .github/workflows/deploy_docs.yml
  docs/hooks/md_image_sizing.py
Labels: documentation, size:M, lgtm

#1585 fix(cec-control): compare variable rather than variable name
  system_files/desktop/shared/usr/bin/cec-control
Labels: bug, size:XS, lgtm

#1588 docs: Replace 'Table of Contents' page with a quick start one
  docs/mkdocs.yml
  docs/src/index.md
Labels: documentation, size:L, lgtm
