Repository ublue-os/bazzite, pull requests merged in 2025-06, with the labels that each got.

#2712 feat: Add German README translation and link
  README-DE.md
  README.md
Labels: documentation, size:L

#2723 feat: improve Bazzite-rebase-helper with interactive TUI
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: enhancement, size:XS

#2741 fix: bazzite-yafti-launcher pointing to non-existent file
  system_files/desktop/shared/usr/libexec/bazzite-yafti-launcher
Labels: bug, size:XS

#2745 fix(ujust): Let Gear lever handle emudeck installation
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: size:S

#2749 fix(flatpak): use system-wide install instead of user
  system_files/desktop/shared/usr/share/ublue-os/just/88-bazzite-webapps.just
Labels: size:XS

#2744 feat: Enable IPv6 privacy extensions
  system_files/desktop/shared/usr/lib/sysctl.d/75-networking.conf
Labels: enhancement, size:XS

#2773 fix: update nvidia-install script to fix builds.
  Containerfile
Labels: bug, size:XS

#2788 chore: Update yafti-go url
  Containerfile
Labels: size:XS

#2789 feat: remove discover knewstuff backend
  Containerfile
Labels: size:XS

#2792 fix: update Renovate file extension to json5
  .github/renovate.json5
Labels: size:XS

#2804 docs: add deepwiki badge
  README.md
Labels: documentation, size:XS, lgtm

#2801 chore(ujust): explicit installation instructions for get-emudeck
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: size:XS, lgtm

#2814 feat: add categories to yafti-go
  system_files/desktop/shared/usr/share/applications/yafti-go.desktop
Labels: size:XS

#2800 chore(brh): Add skopeo caching mechanism
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: size:XS

#2797 ci: replace maximize space with btrfs loopback for podman
  .github/workflows/build.yml
Labels: size:S, lgtm

#2786 feat(nvidia): add CachyOS script to switch to latest dlss preset
  system_files/nvidia/shared/usr/bin/dlss-swapper
  system_files/nvidia/shared/usr/bin/dlss-swapper-dll
Labels: enhancement, size:XS

#2716 ci: build livecd anaconda web-isos
  .github/workflows/build.yml
  .github/workflows/build_iso_titanoboa.yml
  installer/titanoboa_hook_postrootfs.sh
Labels: iso, size:L

#2821 feat: unset net.core.default_qdisc=fq sysctl
  system_files/desktop/shared/usr/lib/sysctl.d/75-networking.conf
Labels: enhancement, size:XS

#2820 fix: change name for livecd workflow
  .github/workflows/build_iso_titanoboa.yml
Labels: iso, size:XS, lgtm

#2823 feat: ujust Mesa-git build and export for game overrides
  Containerfile
  system_files/desktop/shared/usr/share/ublue-os/just/89-bazzite-mesa-git.just
Labels: enhancement, size:L, lgtm
