Repository ublue-os/bazzite, pull requests merged in 2025-04, with the labels that each got.

#2444 feat: add ujust toggle-steamdeck-alias to prevent games from force downloading low quality assets
  system_files/desktop/shared/usr/bin/bazzite-steam
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, steam-deck, size:M, lgtm

#2457 feat: Prevent setup-decky with sudo
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:XS

#2461 Fix: Set -steamdeck alias in gamemode as well as desktop via ujust toggle-steamdeck-alias
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: gamescope, size:S, lgtm

#2469 fix(just): run restorecon for /var/lib/libvirt to fix selinux permissions
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: bug, size:XS

#2470 fix: Always chown homebrew directory when running setup-decky
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: bug, size:S, lgtm

#2462 chore(readme): Remove duplicate 'about' in Press Kit README
  press_kit/README.md
Labels: documentation, size:XS, lgtm

#2477 chore: Remove hyfetch aliases since there's a Brew package for this now
  system_files/desktop/shared/etc/profile.d/bazzite-neofetch.sh
  system_files/overrides/usr/share/fish/vendor_conf.d/bazzite-neofetch.fish
Labels: size:XS

#2481 feat(deck): use uupd on steamos-update script
  system_files/deck/shared/usr/bin/steamos-update
Labels: steam-deck, size:XS

#2489 chore: clean yafti leftover
  system_files/desktop/shared/usr/share/ublue-os/firstboot/launcher/autostart.desktop
  system_files/desktop/shared/usr/share/ublue-os/firstboot/launcher/autostart.sh
  system_files/desktop/shared/usr/share/ublue-os/firstboot/launcher/login-profile.sh
Labels: size:S, lgtm

#2496 feat: add incredibly important, essencial package for bazzite (glorpfetch)
  Containerfile
Labels: enhancement, size:XS

#2502 feat: move to `ublue-brew` for linuxbrew
  Containerfile
  system_files/desktop/shared/usr/lib/systemd/system/brew-dir-fix.service
  system_files/desktop/shared/usr/lib/systemd/system/brew-setup.service
  system_files/desktop/shared/usr/lib/systemd/system/brew-update.service
  system_files/desktop/shared/usr/lib/systemd/system/brew-update.timer
  system_files/desktop/shared/usr/lib/systemd/system/brew-upgrade.service
  system_files/desktop/shared/usr/lib/systemd/system/brew-upgrade.timer
  system_files/desktop/shared/usr/lib/tmpfiles.d/homebrew.conf
Labels: enhancement, size:M

#2520 fix: remove coprs for obs-vkcapture and vk_hdr_layer
  Containerfile
Labels: size:S, lgtm

#2539 chore: use main repo for nvidia-install.sh
  Containerfile
Labels: size:XS

#2542 fix: Ignore unavailabe repos
  Containerfile
Labels: bug, size:S

#2549 chore: remove glorpfetch
  Containerfile
Labels: size:XS, lgtm

#2556 feat: Ujust toggle updates for upcoming yafti replacement
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
  system_files/desktop/shared/usr/share/ublue-os/just/88-bazzite-webapps.just
Labels: enhancement, size:M, lgtm

#2561 Add Noel as a Maintainer
  .github/CODEOWNERS
  .github/FUNDING.yml
Labels: size:XS
