Repository ublue-os/bazzite, pull requests merged in 2025-08, with the labels that each got.

#3005 fix: Update lsfg vk ujust path and ui executable
  system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
Labels: bug, size:M

#3004 fix(desktop): fix ujust-install-jetbrains-toolbox script
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: bug, size:XS

#3011 fix: add folder permission and ownership fix for plugin installers, h…
  Justfile
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
  system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
Labels: bug, size:M, lgtm

#3020 chore: add just syntax check on PRs
  .github/workflows/just-syntax-check.yml
Labels: bug, size:S

#3023 fix: add zeenix handheld to rotation patch (fixes #3002)
  system_files/desktop/shared/etc/default/steamos-nested-desktop
  system_files/desktop/shared/etc/default/waydroid-launcher
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
  system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
  system_files/desktop/shared/usr/libexec/hwsupport/needs-100-scale
  system_files/desktop/shared/usr/libexec/hwsupport/needs-left-rotation
Labels: bug, size:S

#3026 feat: Add framework_tool binary from Framework Computer for handling various hardware features
  Containerfile
Labels: enhancement, size:XS, lgtm

#3040 fix: bazzite-rollback-helper TUI refactor
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: gamescope, size:XS, lgtm

#3043 fix: respect decky permission security change in ujusts
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
  system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
Labels: gamescope, size:M, lgtm

#3047 chore: Remove leftovers of ublue-os-automount udev rules
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: size:S

#3064 fix(gameclass): Add executable permission
  system_files/desktop/shared/usr/bin/gameclass
Labels: bug, size:XS, lgtm

#3061 Fix(gnome): fix `ujust setup-sunshine enable` for gnome desktop
  system_files/desktop/silverblue/etc/systemd/user/sunshine.service.d/override.conf
Labels: sunshine, size:XS, lgtm

#3076 fix(brh): fix rebasing from one signed image to another
  system_files/desktop/shared/usr/bin/bazzite-rollback-helper
Labels: bug, size:XS

#3096 fix(nvidia): missing absolute path for icd workaround
  Containerfile
Labels: bug, size:XS

#3081 chore(coolercontrol): Add layer warning to install recipe
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: size:XS, lgtm

#3118 fix(bazzite-hardware-setup): run fixups commands after applying kargs
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Labels: bug, size:S

#3022 fix: return only one windows boot entry (fixes #3015)
  system_files/desktop/shared/usr/bin/boot-windows
Labels: bug, size:XS, lgtm
