Repository ublue-os/bazzite, pull requests merged in 2025-01, with the labels that each got.

#2046 feat(hhd): add dynamic swap feature
  system_files/deck/shared/usr/lib/systemd/system/hhd@.service.d/override.conf
Labels: enhancement, size:XS

#2047 chore(gamescope): update, fix oxp x1 intel, cleanup
  spec_files/gamescope/1671.patch
  spec_files/gamescope/740.patch
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: size:XXL

#2050 fix(docs): Replace offline docs build action
  .github/workflows/build.yml
  .github/workflows/build_mkdocs/action.yml
Labels: documentation, size:M

#2053 fix(gamescope): revert to previous tag as latest release is busted
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: bug, size:L

#2056 fix(grub): autohide on successful boot
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Labels: bug, size:S, lgtm

#2057 feat(greenboot): Add simpler greenboot variant
  Containerfile
  system_files/deck/shared/usr/lib/systemd/system/bazzite-grub-boot-success.service
  system_files/deck/shared/usr/lib/systemd/system/bazzite-grub-boot-success.timer
  system_files/deck/shared/usr/libexec/bazzite-grub-boot-success
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
  system_files/desktop/shared/usr/libexec/ublue-motd
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
  system_files/desktop/shared/usr/share/ublue-os/motd/bazzite.md
Labels: enhancement, size:L, lgtm

#2062 fix(gamescope): add more fallbacks, remove force fallback, use latest
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: size:L

#2064 fix(steamui): add new video override locations
  system_files/desktop/shared/usr/bin/bazzite-steam
Labels: size:XS, lgtm

#2069 feat: add libvirt qemu hook to setup-virtualization
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: enhancement, size:S

#2068 fix(deck): Fix overwriting Steam videos
  system_files/desktop/shared/usr/bin/bazzite-steam
Labels: size:XS, lgtm

#2075 fix(just): display libvirtd hooks guide after it is downloaded
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: size:XS

#2076 fix: force vfio modules to hopefully load before gpu modules
  system_files/desktop/shared/usr/lib/dracut/dracut.conf.d/80-vfio.conf
Labels: bug, size:XS

#2084 chore(docs): Remove TuneD, update fsync kernel and add a missing point on README-BR
  README-BR.md
Labels: documentation, size:XS

#2089 fix(deck): update 'ujust changelogs' to pull latest release notes from GitHub
  system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
Labels: bug, size:XS, lgtm

#2092 feat: Add 'restore-gamemode-shortcut' and restore 'configure-grub' with ugum styling
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:L, lgtm

#2094 feat: replace steam BPM buitin action
  Containerfile
Labels: enhancement, size:XS, lgtm

#2099 feat(deck): Disable animation replacement for plugins.
  system_files/desktop/shared/usr/bin/bazzite-steam
Labels: enhancement, size:XS, lgtm

#2128 feat: change opentabletdriver installation to flathub version
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: enhancement, size:S, lgtm

#2139 chore(yafti): Remove scrcpy from the Bazzite Portal
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: size:S, lgtm

#2112 fix(docs): Replace offline docs build action (attempt 3)
  .github/workflows/build.yml
  .github/workflows/build_mkdocs/action.yml
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: bug, size:M, lgtm

#2153 feat(gamescope): add legion, cherry hotkey patch, fix externals on Intel rotation
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: enhancement, size:L

#2154 feat(hhd): add new legion dmi
  system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Labels: enhancement, size:XS

#2149 feat(docs): Download docs artifact instead of building
  .github/workflows/build.yml
Labels: size:S, lgtm

#2137 feat: more readable ujust changelogs
  system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
Labels: enhancement, size:XS, lgtm

#2131 feat(waydroid) - Add waydroid force restart shortcut
  system_files/desktop/shared/usr/libexec/waydroid-container-restart
  system_files/desktop/shared/usr/share/applications/waydroid-container-restart.desktop
  system_files/desktop/shared/usr/share/polkit-1/actions/org.bazzite.waydroid.policy
  system_files/desktop/shared/usr/share/polkit-1/rules.d/30-waydroid.rules
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-waydroid.just
Labels: enhancement, size:S, lgtm

#2145 feat(fixes): add toggle-i915-sleep-fix script for power-saving issues #2073)
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
Labels: enhancement, size:M, lgtm

#2136 feat: change openrazer just recipe
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: enhancement, size:S, lgtm

#2116 fix(virt): Enhance service setup and restrict root execution for virtualization script
  system_files/desktop/shared/usr/lib/systemd/system/bazzite-libvirtd-setup.service
  system_files/desktop/shared/usr/lib/tmpfiles.d/bazzite-libvirt.conf
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: bug, size:XS, lgtm

#2157 fix: typo in readable changelogs
  system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
Labels: size:XS

#2166 fix(deck): don't force scaling each time desktop loads
  system_files/deck/shared/usr/bin/bazzite-desktop-bootstrap
Labels: size:XS, lgtm

#2175 chore: add more Legion Go S variants and dedup
  system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Labels: size:XS

#2189 fix: Whole github 404 page was fetched into `/etc/distrobox/incus.ini`
  Containerfile
Labels: bug, size:XS

#2118 feat: easier troubleshooting with 'ujust get-logs', depreciate gamescope-logs
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:M, lgtm

#2186 fix(X1 Pro): fix screen rotation on OneXPlayer X1Pro
  system_files/desktop/shared/usr/libexec/bazzite-hardware-setup
Labels: bug, size:XS, lgtm

#2171 fix (justfile): Add '--reinstall' flag
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: size:XS, lgtm

#2168 fix (docs): Missing GH_TOKEN for pulling offline docs
  .github/workflows/build.yml
Labels: documentation, size:XS, lgtm

#2151 feat: add wake on lan toggle ujust per (#1708)
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
Labels: enhancement, size:M, lgtm

#2191 feat(Containerfile): Migration to dnf5
  Containerfile
  build_files/dnf5-search
Labels: enhancement, size:L

#2194 chore(Containerfile): Fix dnf5-search path
  Containerfile
Labels: size:XS

#2129 feat: 'ujust ssh-toggle' to enable persistent SSH and display Hostname and IP
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:M, lgtm

#2199 chore(Containerfile): More bulletproof config-manager setopt
  Containerfile
  build_files/dnf5-search
  build_files/dnf5-setopt
Labels: size:M

#2197 chore(ci): delete .github/dependabot.yml
  .github/dependabot.yml
Labels: size:S

#2203 chore(Containerfile): Add missing param on dnf5 swap
  Containerfile
Labels: size:XS

#2201 chore(Containerfile): Fix loop logic
  Containerfile
Labels: size:XS

#2210 Restore functioning loop
  Containerfile
Labels: size:XS, lgtm

#2208 feat: add ujust get-framegen
  Containerfile
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
Labels: enhancement, size:L, lgtm

#2205 feat(fcitx5): add `kcm-fcitx5` for better integration with KDE
  Containerfile
Labels: enhancement, size:XS, lgtm

#2211 bugfix(ujust): fix suspend video override ujust
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: bug, size:S, lgtm

#2216 fix(ujust): Remove case sensitivity from configure-watchdog
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: size:XS

#2215 fix(deck): re-add the plugin check for video replacement
  system_files/desktop/shared/usr/bin/bazzite-steam
Labels: bug, steam-deck, size:XS

#2217 fix: restore-gnome-de-settings - indent syntax, handle empty dirs, add error checks
  system_files/deck/silverblue/usr/share/ublue-os/just/90-bazzite-de.just
Labels: size:XS

#2220 fix: rm sudo -A causing plugin install to root
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
Labels: bug, size:XS
