Repository ublue-os/bazzite, pull requests merged in 2025-03, with the labels that each got.

#2328 chore: Bump media-automount-generator 0.2.3 -> 0.2.6
  Containerfile
Labels: dependencies, size:XS, lgtm

#2333 feat: toggle-wol ujust script now dynamically detects active network interface on run
  Containerfile
  system_files/desktop/shared/usr/lib/systemd/system/force-wol.service
  system_files/desktop/shared/usr/libexec/force-wol
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
Labels: enhancement, size:M, lgtm

#2336 feat: Introduce scopebuddy
  system_files/desktop/shared/usr/bin/scb
  system_files/desktop/shared/usr/bin/scopebuddy
Labels: enhancement, size:XS, lgtm

#2342 fix(scopebuddy): rename SCB_DEFAULT_ARGS to SCB_GAMESCOPE_ARGS
  system_files/desktop/shared/usr/bin/scopebuddy
Labels: size:XS

#2343 chore(scopebuddy): remove invalid example option
  system_files/desktop/shared/usr/bin/scopebuddy
Labels: size:XS

#2302 ci: Store buildah build args in a file
  .github/workflows/build.yml
Labels: size:M, lgtm

#2353 fix: Remove leftover quotation in build-args file
  .github/workflows/build.yml
Labels: bug, size:XS, lgtm

#2354 fix: Fetch nct6687 RPM from akmods-extra repository
  build_files/install-kernel-akmods
Labels: size:XS, lgtm

#2358 chore(scopebuddy): remove unused gsout var
  system_files/desktop/shared/usr/bin/scopebuddy
Labels: size:XS

#2362 feat: Switch to upstream scopebuddy
  Containerfile
  system_files/desktop/shared/usr/bin/scb
  system_files/desktop/shared/usr/bin/scopebuddy
Labels: enhancement, size:XS

#2356 feat(yafti): add Crunchyroll and Plex media apps to yafti
  Containerfile
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/lib/systemd/system/force-wol.service
  system_files/desktop/shared/usr/libexec/force-wol
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
  system_files/desktop/shared/usr/share/ublue-os/just/88-bazzite-webapps.just
Labels: enhancement, size:M, lgtm

#2346 fix: remove --no-lock from ujust bazzite-cli brew command
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: bug, size:XS, lgtm

#2364 fix(flatpak): remove flatpak data/icons override
  system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
Labels: bug, size:XS, lgtm

#2357 feat: Smart dnf wrapper
  system_files/overrides/usr/bin/dnf
Labels: enhancement, size:XS, lgtm

#2373 fix: correctly quote KVMFR_MODPROBE heredoc and remove virtqemud_t from type enforcement
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: size:XS

#2374 feat(zone): add zotac gaming zone to supported devices
  system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Labels: enhancement, size:XS

#2376 fix(hdr): Disable PQ HDR on internal panels and add option to disable on externals
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: bug, size:L

#2387 feat: Replace old media-automount-generator package working one
  Containerfile
Labels: enhancement, size:XS

#2384 fix: port changes from dnf to yum
  system_files/overrides/usr/bin/yum
Labels: size:XS

#2389 fix: downgrade dnf5 to avoid regression exposed by Terra
  Containerfile
Labels: bug, size:XS

#2390 ci: move to best-practices config for renovate
  renovate.json
Labels: size:S

#2392 fix: add MSI claw ids
  system_files/desktop/shared/usr/libexec/hwsupport/hhd-supported-hardware
Labels: size:XS

#2394 feat: Change Discover shortcut to launch exclusively using the flatpak backend
  Containerfile
  press_kit/art/Bazzite_Giants.copying
  press_kit/art/Bazzite_Giants.jpg
Labels: enhancement, size:XS

#2395 fix: make CODEOWNERS work
  .github/CODEOWNERS
Labels: bug, size:XS

#2405 fix: kf6-kio package version mismatch due to renaming in Terra
  Containerfile
Labels: bug, size:XS

#2420 fix: discover desktop entry exclusive flatpak backend enablement
  Containerfile
Labels: bug, size:XS

#2424 chore(just): Remove CoolerControl Copr import
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: size:XS, lgtm

#2433 feat: Add ujust enable/disable-automounting
  Containerfile
  system_files/desktop/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: bug, enhancement, size:S

#2416 feat: Add ckb-next
  Containerfile
Labels: enhancement, size:XS, lgtm
