Repository ublue-os/bazzite, pull requests merged in 2025-05, with the labels that each got.

#2572 chore(readme): Remove trailing spaces
  README-BR.md
  README-FR.md
  README-ID.md
  README-NL.md
  README-SPA.md
  README-zh-cn.md
  README.md
Labels: documentation, size:M

#2578 fix: Set flatpak global override for mangohud to writable
  system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
Labels: bug, size:XS

#2579 fix(deck): show oled startup properly
  system_files/desktop/shared/usr/bin/bazzite-steam
  system_files/desktop/shared/usr/bin/bazzite-steam-brand
Labels: steam-deck, size:XS

#2581 chore: remove kcharselect
  Containerfile
Labels: size:XS

#2571 chore: Remove joystickwake leftovers
  README-BR.md
  README-FR.md
  README-NL.md
  README-SPA.md
  README-zh-cn.md
  README.md
  system_files/desktop/kinoite/etc/xdg/autostart/joystickwake.desktop
  system_files/desktop/kinoite/usr/bin/bazzite-joystickwake
Labels: documentation, size:S

#2570 fix(just): Bring back toggle-updates
  system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
Labels: size:S

#2584 chore: fixed restore-gnome-de-settings using sh instead of bash
  system_files/desktop/silverblue/usr/share/ublue-os/just/90-bazzite-de.just
Labels: bug, size:XS

#2594 chore: remove packages from readme since most are outdated
  README-BR.md
  README-FR.md
  README-ID.md
  README-NL.md
  README-SPA.md
  README-zh-cn.md
  README.md
Labels: documentation, size:XL

#2598 chore(distrobox): move to new arch-toolbox tag
  system_files/desktop/shared/etc/distrobox/distrobox.ini
  system_files/nvidia/shared/etc/distrobox/distrobox.ini
Labels: size:XS, lgtm

#2603 fix: update version to work with F42
  .github/workflows/build_iso.yml
Labels: iso, size:XS

#2607 chore:docs: LACT supports more than AMD
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: documentation, size:XS

#2613 chore(ci): remove nokmods from cleanup
  .github/workflows/clean.yml
Labels: size:XS

#2614 fix(ci): remove more dead images
  .github/workflows/clean.yml
Labels: size:XS

#2601 Add russian lang readme
  README-RU.md
  README.md
Labels: documentation, size:L

#2610 feat: Allow smartphone's passkey for chrome browsers
  system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
Labels: enhancement, size:S

#2633 fix(just): Initialize brew into PATH in ujust update
  system_files/desktop/shared/usr/share/ublue-os/just/10-update.just
Labels: bug, size:XS

#2634 fix: Exclude chezmoi from topgrade config
  system_files/desktop/shared/usr/share/ublue-os/topgrade.toml
Labels: size:XS

#2643 feat: Use new media-automount
  Containerfile
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:S

#2635 ci: Add summary of image tags pushed to ghcr
  .github/workflows/build.yml
Labels: size:XS

#2653 fix: update max-performance ujust
  system_files/deck/shared/usr/share/ublue-os/just/85-bazzite-image.just
Labels: size:XS

#2654 fix(desktop): correctly set DefaultTimeoutStopSec
  system_files/desktop/shared/etc/systemd/system.conf.d/timeout.conf
  system_files/desktop/shared/etc/systemd/user.conf.d/timeout.conf
Labels: bug, size:XS

#2639 feat: implement Yafti-Go
  Containerfile
  system_files/desktop/shared/usr/libexec/bazzite-yafti-launcher
  system_files/desktop/shared/usr/share/applications/yafti-go.desktop
  system_files/desktop/shared/usr/share/yafti/yafti.yml
Labels: enhancement, size:L, lgtm

#2656 feat: add uninstall option to Ujust setup-decky
  system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just
Labels: enhancement, size:S

#2661 chore: Remove nicknamenamenick from funding
  .github/FUNDING.yml
Labels: size:XS

#2667 fix: Workaround for gnome file picker
  Containerfile
Labels: bug, size:XS, lgtm

#2670 chore(nvidia): bump nvidia-install.sh
  Containerfile
Labels: size:XS, lgtm

#2683 fix: Yafti desktop update
  system_files/desktop/shared/usr/share/applications/yafti-go.desktop
Labels: size:XS

#2697 feat: ujust get-media-app updates for geforce now
  system_files/desktop/shared/usr/share/ublue-os/just/88-bazzite-webapps.just
  system_files/desktop/shared/usr/share/yafti/yafti.yml
Labels: enhancement, size:L

#2593 ci: Add new retagging action
  .github/workflows/retag.yml
Labels: size:M, lgtm

#2696 feat: automate steam desktop shortcut cleanup
  system_files/desktop/shared/usr/lib/systemd/user/steam-icons-cleanup.service
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
  system_files/desktop/shared/usr/share/yafti/yafti.yml
Labels: enhancement, size:L

#2684 feat: add exit and open web portal opts to ujust setup-sunshine
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-sunshine.just
Labels: sunshine, size:S, lgtm

#2582 feat: Use gnome-disk in all images
  Containerfile
Labels: enhancement, size:XS
