Repository ublue-os/bazzite, pull requests merged in 2025-07, with the labels that each got.

#2842 fix: Modify topgrade to only do a very limited subset of actions
  system_files/desktop/shared/usr/share/ublue-os/topgrade.toml
Labels: size:XS, lgtm

#2854 fix(nvidia): Change dlss-swapper script from CRLF to LF
  system_files/nvidia/shared/usr/bin/dlss-swapper
  system_files/nvidia/shared/usr/bin/dlss-swapper-dll
Labels: bug, size:XS

#2858 chore: remove mention of distrobox in system update shortcut
  system_files/desktop/shared/usr/share/applications/system-update.desktop
Labels: size:XS, lgtm

#2859 fix(bazaar): Run bazaar with the opengl backend
  Containerfile
Labels: bug, size:XS, lgtm

#2866 fix: don't show discover search results
  system_files/desktop/kinoite/etc/xdg/krunnerrc
Labels: size:XS, lgtm

#2876 feat: Live ISOs release
  .github/workflows/build_iso_titanoboa.yml
  installer/titanoboa_hook_postrootfs.sh
  installer/titanoboa_hook_preinitramfs.sh
Labels: iso, size:L, lgtm

#2872 chore(sunshine): fix license version
  spec_files/sunshine/LICENSE
  spec_files/sunshine/sunshine.spec
Labels: sunshine, size:XS, lgtm

#2893 chore: Remove now unneeded udev rule for NTSync
  system_files/desktop/shared/usr/lib/udev/rules.d/95-ntsync.rules
Labels: size:XS, lgtm

#2900 fix(deck): Fix Ally / Ally X HDMI audio cutting out.
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally rc71l_rc71l/wireplumber.conf.d/51-preferHDMI.conf
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally x rc72la_rc72la/wireplumber.conf.d/51-preferHDMI.conf
Labels: bug, size:XS, lgtm

#2901 fix: force-wol script can handle multiple network interfaces
  system_files/desktop/shared/usr/libexec/force-wol
Labels: bug, size:XS

#2910 feat: ujust for lsfg-vk and Lossless Scaling decky plugin install
  system_files/desktop/shared/usr/share/ublue-os/just/87-bazzite-framegen.just
  system_files/desktop/shared/usr/share/yafti/yafti.yml
Labels: enhancement, size:L

#2929 fix(ujust): get-emudeck getting stuck in portal
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: bug, size:XS

#2928 chore(liveiso): More friendly Live ISO text
  installer/titanoboa_hook_postrootfs.sh
Labels: size:XS

#2942 fix(pin): downgrade libdex to 0.9.1
  Containerfile
Labels: bug, size:XS

#2947 fix: Add window icon for gamescope in GNOME
  system_files/desktop/silverblue/usr/share/applications/gamescope.desktop
Labels: gamescope, size:XS, lgtm

#2874 feat: Add gameclass tool for arbitrary game icons
  system_files/desktop/shared/usr/bin/gameclass
Labels: enhancement, size:XS, lgtm

#2969 fix: ensure fedora flatpak repo is disabled
  system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager
Labels: bug, size:XS

#2976 feat(ujust): Add disable-steamos-automount recipe
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
  system_files/desktop/shared/usr/share/yafti/yafti.yml
Labels: enhancement, size:S

#2982 feat(brew): sync brewfile from bluefin-cli
  system_files/overrides/usr/share/ublue-os/homebrew/bazzite-cli.Brewfile
Labels: enhancement, size:XS
