Repository ublue-os/bazzite, pull requests merged in 2025-02, with the labels that each got.

#2227 chore(TuneD): Move tweaks to inherit upstream
  system_files/desktop/shared/etc/tuned/ppd.conf
  system_files/desktop/shared/etc/tuned/profiles/balanced-bazzite/tuned.conf
  system_files/desktop/shared/etc/tuned/profiles/throughput-performance-bazzite/tuned.conf
  system_files/desktop/shared/usr/lib/tuned/profiles/balanced/tuned.conf
  system_files/desktop/shared/usr/lib/tuned/profiles/throughput-performance/tuned.conf
Labels: size:L, lgtm

#2224 feat: add firewall-config (GUI) for GNOME
  Containerfile
Labels: enhancement, size:XS

#2221 feat: add udev rules to just recipe opentabletdriver
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: enhancement, size:S, lgtm

#2207 feat: add USB hot plugging configuration for virtualization script
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: enhancement, size:S, lgtm

#2235 feat: Trim Lutris dependencies
  Containerfile
Labels: enhancement, size:S

#2239 chore(ci): support combined akmods-kernel-cache in build
  Containerfile
Labels: size:XS

#2241 fix: add back snapper
  Containerfile
Labels: size:XS

#2242 fix: block LVFS on the Legion Go S for now
  system_files/deck/shared/fwupd/fwupd.conf
Labels: size:XS

#2246 fix(gamescope): fix rotation shader messing with input devices on intel
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: bug, size:M, lgtm

#2245 fix(just): add correct path for libvirt hooks
  system_files/desktop/shared/usr/share/ublue-os/just/84-bazzite-virt.just
Labels: bug, size:XS

#2257 fix(deck): move hid preload from ds-inhibit to sysfiles and add hid-nintendo
  spec_files/ds-inhibit/10-modprobe-ds.conf
  spec_files/ds-inhibit/ds-inhibit.spec
  system_files/deck/shared/etc/modules-load.d/hid-steaminput-preload.conf
Labels: steam-deck, size:S

#2255 fix: only run bazzite-user-setup for human users
  system_files/desktop/shared/usr/lib/systemd/user/bazzite-user-setup.service
Labels: size:XS, lgtm

#2259 fix(deck): import proton niceness setting from steamos
  system_files/deck/shared/etc/security/rules.d/15-proton-nice.conf
Labels: steam-deck, size:XS

#2253 fix: Fix incorrect completions path
  system_files/overrides/usr/share/fish/vendor_conf.d/brew.fish
Labels: bug, size:XS, lgtm

#2263 chore(docs): Revise README-BR with recent changes
  README-BR.md
Labels: documentation, size:XS

#2264 chore: Remove unnecessary git installation
  Containerfile
Labels: size:XS

#2269 chore: Update testing to have main's changes
  README-BR.md
  README.md
Labels: size:XS

#2265 feat(scx_loader): Add config file for scx_loader
  system_files/desktop/shared/etc/scx_loader/config.toml
Labels: enhancement, size:S

#2288 fix(mangohud): Add patch for uninitialized GPUs
  spec_files/mangohud/dont_crash_gpu_uninit.patch
  spec_files/mangohud/mangohud.spec
Labels: bug, size:M

#2293 fix(deck): Default to HDMI audio for the ROG Ally
  system_files/deck/shared/usr/share/wireplumber/hardware-profiles/asustek computer inc.-rog ally rc71l_rc71l/wireplumber.conf.d/51-preferHDMI.conf
Labels: size:S

#2287 chore(just): Replace docker distrobox with a docker cli hooked to podman socket
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: size:M

#2223 feat: Ujust scripts for Cloud apps (Xbox Cloud Gaming, others?)
  Containerfile
  system_files/deck/shared/usr/share/ublue-os/firstboot/yafti.yml
  system_files/desktop/shared/usr/share/ublue-os/just/88-bazzite-webapps.just
Labels: enhancement, size:L, lgtm

#2300 chore(docs): Fix README-BR double space
  README-BR.md
Labels: documentation, size:XS, lgtm

#2307 feat(gamescope): add z13 display config
  spec_files/gamescope/gamescope.spec
  spec_files/gamescope/handheld.patch
Labels: enhancement, size:L

#2315 fix: Correctly detect if WOL is enabled and correctly create force-wol service file when create-service is choosen
  system_files/desktop/shared/usr/share/ublue-os/just/81-bazzite-fixes.just
Labels: bug, size:S

#2317 feat: Update kernel to 6.13.5-100
  .github/workflows/build.yml
Labels: size:XS

#2327 feat: Update kernel to 6.13.5-102
  .github/workflows/build.yml
Labels: size:XS

#2325 docs: Remove Gradience from README.md
  README.md
Labels: documentation, size:XS, lgtm

#2324 fix: brew file conflict when installing docker plugins
  system_files/desktop/shared/usr/share/ublue-os/just/82-bazzite-apps.just
Labels: bug, size:S, lgtm

#2319 docs: More informative error prompt for dnf wrapper
  system_files/overrides/usr/bin/dnf
Labels: size:XS, lgtm
